# Generated by Django 5.2.3 on 2025-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.TextField(default='США', max_length=30),
        ),
    ]
