# Generated by Django 5.2.3 on 2025-06-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default='Z0', max_length=100),
            preserve_default=False,
        ),
    ]
