# Generated by Django 5.2.3 on 2025-07-01 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_booking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
