# Generated by Django 5.2.3 on 2025-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_movie_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='row',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='vip_rows',
            field=models.CharField(blank=True, default='', help_text='Список номеров VIP рядов через запятую, например: 1,2,5', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
