# Generated by Django 5.2.3 on 2025-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_booking_row_hall_vip_rows_session_vip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
